name: SPM

on:
  release:
    types: [published]
  repository_dispatch:

env:
  REPO: ${{ github.event.repository.name }}
  SERVICE: sportbuff-ios-spm
  IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
  ZIP_CHECKSUM: ${{ github.event.client_payload.checksum }}
  TOKEN: ${{ secrets.GH_TOKEN }}

concurrency:
  group: merge
  cancel-in-progress: false

jobs:
  spm:
    name: Upload Swift Package
    runs-on: macos-12

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Echo Variables
        run: |
          echo "IMAGE_TAG:"
          echo ${{ env.IMAGE_TAG }}
          echo "ZIP_CHECKSUM:"
          echo ${{ env.ZIP_CHECKSUM }}

      - name: Create Swift Package
        run: |
          export CHECKSUM="${{ env.ZIP_CHECKSUM }}"
          export TAG="${{ env.IMAGE_TAG }}"
          echo $CHECKSUM
          echo $TAG
          sed "s/URL/https:\/\/buffup-public.s3.eu-west-2.amazonaws.com\/ios-sdk\/sportbuff-ios-sdk-$TAG.zip/g" Package.tpl | sed "s/CHECKSUM/$CHECKSUM/g" > Package.swift
          cat Package.swift

      - name: Push Package.swift
        uses: EndBug/add-and-commit@v7
        with:
          add: '-u .'
          default_author: 'github_actions'
          message: 'Commit new version v: ${{ env.IMAGE_TAG }}'
          branch: 'main'
          tag: '${{ env.IMAGE_TAG }} --force'
